"""Add warehouse_id to users

Revision ID: 384d91871300
Revises: a0f94a398d8b
Create Date: 2026-07-21 14:43:13.958396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384d91871300'
down_revision: Union[str, None] = 'a0f94a398d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('inventory_snapshots') as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='True if this is the active operational snapshot.'))
        batch_op.drop_constraint('uq_inv_snapshot_mat_wh_date', type_='unique')
        batch_op.create_unique_constraint('uq_inv_snapshot_mat_wh_date_ver', ['material_id', 'warehouse_id', 'snapshot_date', 'version'])

    with op.batch_alter_table('notifications') as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=500), nullable=True))
        # Note: changing column types is risky in SQLite but we aren't changing type, we just renamed it previously or changed length. Actually, let's just ignore the text->varchar change.
        batch_op.drop_column('title')

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.BigInteger(), nullable=True, comment='Primary warehouse assignment for inventory operations.'))
        batch_op.create_foreign_key('fk_users_warehouses', 'warehouses', ['warehouse_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_warehouses', type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('notifications') as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False, server_default=''))
        batch_op.drop_column('link')

    with op.batch_alter_table('inventory_snapshots') as batch_op:
        batch_op.drop_constraint('uq_inv_snapshot_mat_wh_date_ver', type_='unique')
        batch_op.create_unique_constraint('uq_inv_snapshot_mat_wh_date', ['material_id', 'warehouse_id', 'snapshot_date'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
