"""Workflow refinements and Notifications

Revision ID: a0f94a398d8b
Revises: e1ca08b6a998
Create Date: 2026-07-20 19:26:53.490738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f94a398d8b'
down_revision: Union[str, None] = 'e1ca08b6a998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_request_history',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['material_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mat_req_history_req_id', 'material_request_history', ['request_id'], unique=False)
    op.create_index(op.f('ix_material_request_history_public_id'), 'material_request_history', ['public_id'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.add_column('material_requests', sa.Column('request_number', sa.String(length=50), nullable=True))
    op.add_column('material_requests', sa.Column('review_comments', sa.Text(), nullable=True))
    op.create_index(op.f('ix_material_requests_request_number'), 'material_requests', ['request_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_requests_request_number'), table_name='material_requests')
    op.drop_column('material_requests', 'review_comments')
    op.drop_column('material_requests', 'request_number')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_material_request_history_public_id'), table_name='material_request_history')
    op.drop_index('ix_mat_req_history_req_id', table_name='material_request_history')
    op.drop_table('material_request_history')
    # ### end Alembic commands ###
