"""Initial

Revision ID: b5e8b2c0270a
Revises: 
Create Date: 2026-07-20 15:13:46.929463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'b5e8b2c0270a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('bom_upload_sessions',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('import_results', sa.JSON(), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_upload_sessions_public_id'), 'bom_upload_sessions', ['public_id'], unique=True)
    op.create_table('business_event_logs',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('triggered_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_biz_event_logs_created_at', 'business_event_logs', ['created_at'], unique=False)
    op.create_index('ix_biz_event_logs_event_type', 'business_event_logs', ['event_type'], unique=False)
    op.create_index('ix_biz_event_logs_reference', 'business_event_logs', ['reference_type', 'reference_id'], unique=False)
    op.create_table('material_categories',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_material_categories_name'),
    sa.UniqueConstraint('public_id', name='uq_material_categories_public_id')
    )
    op.create_index(op.f('ix_material_categories_public_id'), 'material_categories', ['public_id'], unique=True)
    op.create_table('material_groups',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_material_groups_name'),
    sa.UniqueConstraint('public_id', name='uq_material_groups_public_id')
    )
    op.create_index(op.f('ix_material_groups_public_id'), 'material_groups', ['public_id'], unique=True)
    op.create_table('material_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_material_types_name'),
    sa.UniqueConstraint('public_id', name='uq_material_types_public_id')
    )
    op.create_index(op.f('ix_material_types_public_id'), 'material_types', ['public_id'], unique=True)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_permissions_code'),
    sa.UniqueConstraint('public_id', name='uq_permissions_public_id')
    )
    op.create_index(op.f('ix_permissions_public_id'), 'permissions', ['public_id'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_roles_name'),
    sa.UniqueConstraint('public_id', name='uq_roles_public_id')
    )
    op.create_index(op.f('ix_roles_public_id'), 'roles', ['public_id'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False, comment='One of: string | integer | float | boolean | json'),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_settings_key'),
    sa.UniqueConstraint('public_id', name='uq_settings_public_id')
    )
    op.create_index('ix_settings_key', 'settings', ['key'], unique=False)
    op.create_index(op.f('ix_settings_public_id'), 'settings', ['public_id'], unique=True)
    op.create_table('skus',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_skus_code'),
    sa.UniqueConstraint('public_id', name='uq_skus_public_id')
    )
    op.create_index(op.f('ix_skus_public_id'), 'skus', ['public_id'], unique=True)
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('ODS', 'RMPM')", name='ck_warehouses_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_warehouses_name'),
    sa.UniqueConstraint('public_id', name='uq_warehouses_public_id')
    )
    op.create_index(op.f('ix_warehouses_public_id'), 'warehouses', ['public_id'], unique=True)
    op.create_table('bom_versions',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'version_number', name='uq_bom_versions_sku_ver')
    )
    op.create_index(op.f('ix_bom_versions_public_id'), 'bom_versions', ['public_id'], unique=True)
    op.create_index('ix_bom_versions_sku_id', 'bom_versions', ['sku_id'], unique=False)
    op.create_table('material_requests',
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('ods_warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('rmpm_warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('SUBMITTED', 'RESERVED', 'APPROVED', 'PARTIALLY_APPROVED', 'DISPATCHED', 'RECEIVED', 'CLOSED', 'REJECTED')", name='ck_material_requests_status'),
    sa.ForeignKeyConstraint(['ods_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rmpm_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_material_requests_public_id')
    )
    op.create_index(op.f('ix_material_requests_public_id'), 'material_requests', ['public_id'], unique=True)
    op.create_index('ix_material_requests_status_date', 'material_requests', ['status', 'created_at'], unique=False)
    op.create_table('materials',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=False, comment='Unit of measure: kg, L, units, etc.'),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['material_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['material_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['material_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_materials_code'),
    sa.UniqueConstraint('public_id', name='uq_materials_public_id')
    )
    op.create_index('ix_materials_category_id', 'materials', ['category_id'], unique=False)
    op.create_index(op.f('ix_materials_public_id'), 'materials', ['public_id'], unique=True)
    op.create_index('ix_materials_type_id', 'materials', ['type_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_perm')
    )
    op.create_index(op.f('ix_role_permissions_public_id'), 'role_permissions', ['public_id'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False, comment='Consecutive failed login attempts since last successful login.'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this UTC time. NULL = not locked.'),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('public_id', name='uq_users_public_id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index('ix_users_role_id', 'users', ['role_id'], unique=False)
    op.create_table('bom_items',
    sa.Column('bom_version_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=18, scale=4), nullable=False, comment='Material qty required to produce 1 unit of the parent SKU.'),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_per_unit > 0', name='ck_bom_items_qty_positive'),
    sa.ForeignKeyConstraint(['bom_version_id'], ['bom_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_version_id', 'material_id', name='uq_bom_items_ver_mat')
    )
    op.create_index('ix_bom_items_bom_version_id', 'bom_items', ['bom_version_id'], unique=False)
    op.create_index('ix_bom_items_material_id', 'bom_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_bom_items_public_id'), 'bom_items', ['public_id'], unique=True)
    op.create_table('inventory_snapshots',
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=4), nullable=False, comment='Sum of all transactions up to and including snapshot_date.'),
    sa.Column('reserved_balance', sa.Numeric(precision=18, scale=4), nullable=False, comment='Quantity currently reserved but not yet dispatched.'),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('closing_balance >= 0', name='ck_inv_snapshot_balance_non_neg'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'warehouse_id', 'snapshot_date', name='uq_inv_snapshot_mat_wh_date')
    )
    op.create_index('ix_inv_snapshot_date', 'inventory_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_inv_snapshot_material_warehouse', 'inventory_snapshots', ['material_id', 'warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_public_id'), 'inventory_snapshots', ['public_id'], unique=True)
    op.create_table('inventory_transactions',
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('source_warehouse_id', sa.BigInteger(), nullable=True, comment='NULL for pure RECEIPT transactions.'),
    sa.Column('destination_warehouse_id', sa.BigInteger(), nullable=True, comment='NULL for pure DISPATCH transactions.'),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment="E.g., 'MATERIAL_REQUEST', 'EOD_COUNT', 'OPENING_BALANCE'."),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('RECEIPT','DISPATCH','ADJUSTMENT','TRANSFER_OUT','TRANSFER_IN','RESERVATION','RESERVATION_RELEASE','CONSUMPTION')", name='ck_inv_tx_type'),
    sa.CheckConstraint('quantity > 0', name='ck_inv_tx_qty_positive'),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_tx_created_at', 'inventory_transactions', ['created_at'], unique=False)
    op.create_index('ix_inv_tx_destination', 'inventory_transactions', ['destination_warehouse_id'], unique=False)
    op.create_index('ix_inv_tx_material_warehouse', 'inventory_transactions', ['material_id', 'source_warehouse_id'], unique=False)
    op.create_index('ix_inv_tx_reference', 'inventory_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_table('material_request_skus',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('planned_production_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('bom_version_id', sa.BigInteger(), nullable=False, comment='Snapshot of the BOM version used at request time.'),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('planned_production_qty > 0', name='ck_material_request_skus_qty_pos'),
    sa.ForeignKeyConstraint(['bom_version_id'], ['bom_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['material_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mat_req_sku_request_id', 'material_request_skus', ['request_id'], unique=False)
    op.create_index('ix_mat_req_sku_sku_id', 'material_request_skus', ['sku_id'], unique=False)
    op.create_index(op.f('ix_material_request_skus_public_id'), 'material_request_skus', ['public_id'], unique=True)
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False, comment='JWT ID claim from the refresh token (UUID).'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False, comment='True if this session was explicitly revoked (logout).'),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti', name='uq_refresh_sessions_jti')
    )
    op.create_index('ix_refresh_sessions_jti', 'refresh_sessions', ['jti'], unique=False)
    op.create_index('ix_refresh_sessions_user_id', 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('material_request_items',
    sa.Column('request_sku_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('gross_required_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='= BOM quantity × planned_production_qty'),
    sa.Column('remaining_from_previous_day', sa.Numeric(precision=18, scale=4), nullable=False, comment='Physically counted leftover from the previous day.'),
    sa.Column('requested_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='= gross_required_qty - remaining_from_previous_day'),
    sa.Column('approved_qty', sa.Numeric(precision=18, scale=4), nullable=True, comment='Set by RMPM operator during approval. NULL = not yet approved.'),
    sa.Column('dispatched_qty', sa.Numeric(precision=18, scale=4), nullable=True, comment='Set by RMPM operator during dispatch.'),
    sa.Column('received_qty', sa.Numeric(precision=18, scale=4), nullable=True, comment='Set by ODS operator during receive.'),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('approved_qty IS NULL OR approved_qty >= 0', name='ck_mat_req_item_appr_qty_non_neg'),
    sa.CheckConstraint('remaining_from_previous_day >= 0', name='ck_mat_req_item_remaining_non_neg'),
    sa.CheckConstraint('requested_qty >= 0', name='ck_mat_req_item_req_qty_pos'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_sku_id'], ['material_request_skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mat_req_items_material_id', 'material_request_items', ['material_id'], unique=False)
    op.create_index('ix_mat_req_items_request_sku_id', 'material_request_items', ['request_sku_id'], unique=False)
    op.create_index(op.f('ix_material_request_items_public_id'), 'material_request_items', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_request_items_public_id'), table_name='material_request_items')
    op.drop_index('ix_mat_req_items_request_sku_id', table_name='material_request_items')
    op.drop_index('ix_mat_req_items_material_id', table_name='material_request_items')
    op.drop_table('material_request_items')
    op.drop_index('ix_refresh_sessions_user_id', table_name='refresh_sessions')
    op.drop_index('ix_refresh_sessions_jti', table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_material_request_skus_public_id'), table_name='material_request_skus')
    op.drop_index('ix_mat_req_sku_sku_id', table_name='material_request_skus')
    op.drop_index('ix_mat_req_sku_request_id', table_name='material_request_skus')
    op.drop_table('material_request_skus')
    op.drop_index('ix_inv_tx_reference', table_name='inventory_transactions')
    op.drop_index('ix_inv_tx_material_warehouse', table_name='inventory_transactions')
    op.drop_index('ix_inv_tx_destination', table_name='inventory_transactions')
    op.drop_index('ix_inv_tx_created_at', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_snapshots_public_id'), table_name='inventory_snapshots')
    op.drop_index('ix_inv_snapshot_material_warehouse', table_name='inventory_snapshots')
    op.drop_index('ix_inv_snapshot_date', table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_bom_items_public_id'), table_name='bom_items')
    op.drop_index('ix_bom_items_material_id', table_name='bom_items')
    op.drop_index('ix_bom_items_bom_version_id', table_name='bom_items')
    op.drop_table('bom_items')
    op.drop_index('ix_users_role_id', table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_public_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_materials_type_id', table_name='materials')
    op.drop_index(op.f('ix_materials_public_id'), table_name='materials')
    op.drop_index('ix_materials_category_id', table_name='materials')
    op.drop_table('materials')
    op.drop_index('ix_material_requests_status_date', table_name='material_requests')
    op.drop_index(op.f('ix_material_requests_public_id'), table_name='material_requests')
    op.drop_table('material_requests')
    op.drop_index('ix_bom_versions_sku_id', table_name='bom_versions')
    op.drop_index(op.f('ix_bom_versions_public_id'), table_name='bom_versions')
    op.drop_table('bom_versions')
    op.drop_index(op.f('ix_warehouses_public_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_skus_public_id'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_settings_public_id'), table_name='settings')
    op.drop_index('ix_settings_key', table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_roles_public_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_public_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_material_types_public_id'), table_name='material_types')
    op.drop_table('material_types')
    op.drop_index(op.f('ix_material_groups_public_id'), table_name='material_groups')
    op.drop_table('material_groups')
    op.drop_index(op.f('ix_material_categories_public_id'), table_name='material_categories')
    op.drop_table('material_categories')
    op.drop_index('ix_biz_event_logs_reference', table_name='business_event_logs')
    op.drop_index('ix_biz_event_logs_event_type', table_name='business_event_logs')
    op.drop_index('ix_biz_event_logs_created_at', table_name='business_event_logs')
    op.drop_table('business_event_logs')
    op.drop_index(op.f('ix_bom_upload_sessions_public_id'), table_name='bom_upload_sessions')
    op.drop_table('bom_upload_sessions')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
