"""Make email nullable

Revision ID: ce805782f353
Revises: c3f1a2b9d4e5
Create Date: 2026-07-22 00:08:30.544467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce805782f353'
down_revision: Union[str, None] = 'c3f1a2b9d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('business_event_logs', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('inventory_snapshots', 'version',
               existing_type=sa.INTEGER(),
               comment='Version number for audit trail.',
               existing_nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Account locked until this UTC time. NULL = not locked. Auto-lockout only.',
               existing_comment='Account locked until this UTC time. NULL = not locked.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Account locked until this UTC time. NULL = not locked.',
               existing_comment='Account locked until this UTC time. NULL = not locked. Auto-lockout only.',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('inventory_snapshots', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Version number for audit trail.',
               existing_nullable=False)
    op.alter_column('business_event_logs', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
