"""Add dispatched received quantities and warehouse ids

Revision ID: df1a4b0d0685
Revises:
Create Date: 2026-07-12 19:39:26.192770

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df1a4b0d0685"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "material_request_items",
        sa.Column(
            "dispatched_qty",
            sa.Numeric(precision=18, scale=4),
            nullable=True,
            comment="Set by RMPM operator during dispatch.",
        ),
    )
    op.add_column(
        "material_request_items",
        sa.Column(
            "received_qty",
            sa.Numeric(precision=18, scale=4),
            nullable=True,
            comment="Set by ODS operator during receive.",
        ),
    )
    op.add_column(
        "material_requests",
        sa.Column("ods_warehouse_id", sa.BigInteger(), nullable=False),
    )
    op.add_column(
        "material_requests",
        sa.Column("rmpm_warehouse_id", sa.BigInteger(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "material_requests",
        "warehouses",
        ["ods_warehouse_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "material_requests",
        "warehouses",
        ["rmpm_warehouse_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("material_requests", "rmpm_warehouse_id")
    op.drop_column("material_requests", "ods_warehouse_id")
    op.drop_column("material_request_items", "received_qty")
    op.drop_column("material_request_items", "dispatched_qty")
    # ### end Alembic commands ###
