"""Add warnings to bom_upload_sessions

Revision ID: e1ca08b6a998
Revises: b5e8b2c0270a
Create Date: 2026-07-20 17:36:35.098407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ca08b6a998'
down_revision: Union[str, None] = 'b5e8b2c0270a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_upload_sessions', sa.Column('warnings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bom_upload_sessions', 'warnings')
    # ### end Alembic commands ###
